linux-application-whitelisting/fapolicyd

- doc/fapolicyd.8
- src/fapolicyd.c
Some minor fixes to the command line options processing logic. Found that passing values to the options 'boost' and 'queue' had caused the program to crash with a segmentation fault. Seeing as though most these command line options can also be set via the fapolicyd configuration file, I thought it'd make sense to align the logic with what has been defined for the parsers within src/daemon-config.c (specifically referring to the setting of the niceness here).
Also, rather than actually just assigning gid = uid, I thought it'd be better actually obtaining the primary group id of the user and using that when the 'user' command line option is used.
> Fixes applied to command line options parsing to stop program crashing

- doc/fapolicyd.8
- doc/fapolicyd.rules.5
Fixes for a few typos in manpages:
vaious/various
meay/may
performeance/performance 
foresics/forensics
obbject/object
Apologies, I should have bundled all corrections together.
> Fixes for a few typos

- src/database.c
- src/fapolicyd-cli.c
- fapolicyd-cli requires fapolicyd.fifo to have 0660 permissions
> Change fifo mode to 0660

- src/database.c
- src/file.c
- src/file.h
MDB_MAXKEYSIZE is set to 511 bytes. 
Store a file by path if the length is less than 490. If the previous condition is false, we convert it to hash using sha256. The very first character of the string indicates:
- "/" path
- "some number"  hash
> Handle long paths by hashing it (lmdb has 511 byte limit).

- src/event.c
- src/rules.c
- src/subject-attr.c
- src/subject-attr.h
Subject cache "remember" whether subject itself was/is trusted.
I hope this should help with performance. 
I will try to apply this to object cache but in some other PR.
> Subject cache contains trust information

- src/database.c
Move 'data miscompare' message to debug.
It occurs almost every time you rebuild a db. It is a debug info not needed when you hit systemctl status.
> Message redirect from warning to debug

- doc/Makefile.am
- doc/fapolicyd.conf.5
- doc/fapolicyd.trust.5
- fapolicyd.spec
- init/Makefile.am
- init/fapolicyd.conf
- init/fapolicyd.trust
- src/Makefile.am
- src/daemon/daemon-config.c
- src/daemon/fapolicyd.c
- src/library/backend-manager.c
- src/library/backend-manager.h
- src/library/conf.h
- src/library/database.c
- src/library/fapolicyd-backend.h
- src/library/file-backend.c
- src/library/llist.c
- src/library/llist.h
- src/library/rpm-backend.c
This PR introduces a possibility to set and manage multiple trust back-ends. Admin can choose between two available options which are ```rpmdb``` and ```file``` or use both. Trust back-end can be set in daemon configuration.
The set of back-ends is expandable very easily via interface located in ```src/library/fapolicyd-backend.h```.
> Switchable trust back-ends

- src/library/database.c
- src/library/event.c
- src/library/event.h
Thanks to thread sanitizer and valgrind I've discovered
and fixed these few issues related to thread synchronization.
- update_lock was used before its initialization
- check_trust_database() could read from database even when
update thread locked resources and it was providing an update
- calling flush_cache() from update thread wasn't good idea
since the resource owner was decision thread
- update thread now only signals event system that cache should
be flushed and this is checked within new_event()
> Fixed threads synchronization

- src/library/event.c
- mark every subject and object as not trusted
when it is not possible to do a query
- previously, when error occurred then subject or
object was actually considered to be trusted
> Ignore db errors from check_trust_database()

- doc/fapolicyd.conf.5
> Sync fapolicyd.conf man page trust option with the real default.

- ChangeLog
- doc/fapolicyd.rules.5
- src/library/process.c
- src/library/process.h
- src/library/rules.c
This patch adds support to detect LD_PRELOAD and LD_AUDIT usage. It will
prevent execution if either are detected in the application's environment.
This will override any trust qualifications for the library being preloaded.
> Re-implement LD_PRELOAD detection

- src/daemon/notify.c
- src/library/policy.c
Fix for issue #83.  Moved the metadata fd close call to happen right before the call to write in make_policy_decision and approve_event and removed it from happening after the call to make_policy_decision.
> Move metadata fd close call

- fapolicyd.spec
- src/library/database.c
- src/library/rpm-backend.c
Getting rid of the duplicate records from RPM
- checking duplicates with hash table when
creating a list in rpmdb backend
- uthash-devel package is the new dependency
- as a sidefect we can detect when db is a superset
of what is available from the backend
Usecase:
- when a file is added via cli as trusted, during startup `check_database_copy()` detects a new file which is not part of the db
- on the other hand when we remove the file from the trust list, `check_database_copy()` is not able to detect that file was removed it remains in db and it is considered to be trusted even after restart of the daemon
> DB superset check

- src/library/rpm-backend.c
`.java` files themselves aren't directly executable using the default `java`
program; instead, they must first be compiled to `.class` files (using
`javac`) before they can be executed via java. This means that `.java` files
shipped in RPMs (as say, API usage examples) won't be executed and don't
necessarily need to be. They could however, be compiled first and then
executed as `.class`; however, this resulting `.class` file should likely be
somewhere other than `/usr/share` if it wasn't distributed by the RPM
itself.
`Signed-off-by: Alexander Scheel <ascheel@redhat.com>`
---
@stevegrubb -- should we allow both?
> Allow .class files instead of .java files

- src/library/database.c
Enhance the algorithm and check for multiple duplicates.
> Support multiple duplicates in DB

- src/library/database.c
- one can write record/s to pipe in following format
- "%s %ul %64s\n"
- it contains full path, size and sha256 hash
- each record has to be terminated with new line character
- size of the record is limited by size of the buffer which is 4096
- one can write "2" to the pipe and daemon will flush all cache
- it is recommended to refresh the caches after some addition
> Added support for dynamic trust records

- src/cli/fapolicyd-cli.c
- MDB_NOLOCK option resolves the issue with --dump-db hang
-  closes #113 
> Added MDB_NOLOCK to cli mdb_env_open()

- src/library/database.c
- introduced in 128e22d0c638aed81337a6dbbfa664e5bfc9ea06
- daemon does not start when unlinking non existing db
- fapolicyd-cli returned error when there is no db to unlink
> Fixed problem with startup failed on unlink()

- src/Makefile.am
Due to an oversight, the RPM backend is built unconditionally. It seems that when the option to use `--without-rpm` was added, it was not removed from the normal build.
> Fix build failure with '--without-rpm'

- doc/fapolicyd-cli.1
- fapolicyd.spec
- src/Makefile.am
- src/cli/fapolicyd-cli.c
- src/cli/file-cli.c
- src/cli/file-cli.h
- src/library/file-backend.c
- src/library/llist.c
- src/library/llist.h
- src/library/string-util.c
- src/library/string-util.h
- src/library/trust-file.c
- src/library/trust-file.h
This commit implements trust.d directory.
What exactly changed:
-  after installing fapolicyd a trust.d directory is created inside /etc/fapolicyd/ with 750 permissions.
-  **fapolicyd-cli --file add path** now appends into fapolicyd.trust file located inside /etc/fapolicyd/ by default
- **fapolicyd-cli --file delete path** deletes a path from all trust files by default. ie. it deletes path from fapolicyd.trust + all of the trust files located inside trust.d directory
- **fapolicyd-cli --file update path** updates a path in all trust files by default
- user can now use option **--trust-file file-name** after **--file** to specify a trust file inside a trust.d directory to operate on
Example usage:
**fapolicyd-cli --file add path --trust-file fname**
this will append a path **path** into a …
> Add trust.d directory

- src/library/file.c
Current libc/pthread detection:
/usr/lib
/usr/lib64
Add directories
/lib
/lib64
> Expand sharedlib detection

- src/Makefile.am
- src/library/escape.c
- src/library/escape.h
- src/library/trust-file.c
- content of the trust file needs to be escaped
- problematic characters [in file name] are usually whitespaces
- '%' char is used for escaping
- escape sequence looks like following: "%3A" which stands for 1 byte
where '3' stands for higher 4 bits in hex and 'A' stands for lower 4
bits of the byte, space can be escaped as "%20" and '%' is "%25"
> Implement escaping capability

- README.md
Add instructions to install build-time dependencies for Fedora and RHEL8 in a way that is cut-and-paste friendly.
> README includes dependency install instructions

- src/library/file.c
Fixes following warnings:
```
In function ‘safe_read’,
inlined from ‘read_header32’ at library/file.c:504:15,
inlined from ‘gather_elf’ at library/file.c:560:21:
library/file.c:409:23: warning: ‘read’ writing 36 bytes into a region of size 2 overflows the destination [-Wstringop-overflow=]
409 |                 len = read(fd, buf, size);
|                       ^~~~~~~~~~~~~~~~~~~
In file included from library/file.c:37:
library/file.c: In function ‘gather_elf’:
/usr/include/elf.h:66:17: note: destination object ‘e_type’ of size 2
66 |   Elf32_Half    e_type;                 /* Object file type */
|                 ^~~~~~
In file included from library/file.c:30:
/usr/include/unistd.h:371:16: note: in a call to function ‘read’ declared with attribute ‘access (write_only, 2, 3)’
371 | …
```
> Fix compiler warnings

- fapolicyd.spec
Use normal macros
Use find -delete when removing files
After installing and running package:
```
rpm -V <packagename>
```
should not provide any regressions if user did not modify any file.
```
% sudo rpm -V fapolicyd
.M....G..  g /run/fapolicyd/fapolicyd.fifo
.M...UG..  g /var/lib/fapolicyd/data.mdb
.M...UG..  g /var/lib/fapolicyd/lock.mdb
.M...UG..  g /var/log/fapolicyd-access.log
```
```
% sudo ls -lad /var/lib/fapolicyd/data.mdb /var/lib/fapolicyd/lock.mdb /var/log/fapolicyd-access.log
-rw-rw----. 1 fapolicyd fapolicyd 41943040 29.12. 21:31 /var/lib/fapolicyd/data.mdb
-rw-rw----. 1 fapolicyd fapolicyd      384 29.12. 21:31 /var/lib/fapolicyd/lock.mdb
-r--r-----. 1 fapolicyd fapolicyd    12545 29.12. 21:31 /var/log/fapolicyd-access.log
% sudo ls -lad /run/fapolicyd/fapolicyd.fifo …
```
> Some spec nitpicks

- init/fapolicyd.rules.known-libs
- init/fapolicyd.rules.restrictive
Ansible is currently using /var/tmp directory to store its python scripts. There is already a dracut rule that allows this directory.
> Remove unnecessary ansible rules

- src/library/file.c
Expand libc detection to detect simlinks like /lib64/libc.so.0 etc.
> Expand libc sharedlib detection

- fapolicyd.spec
- otherwise rpm will move the file to .rpmsave when there are changes
- and there is no fapolicyd.trust nor compiled.rules
> fapolicyd.rules needs to be ghost file

- src/daemon/notify.c
When the internal event queue fills, we do not close the event's file descriptor, which results in the process accumulating them over time if the queue size is not properly configured.
> Close event file descriptor on enqueue failure

- src/cli/fapolicyd-cli.c
- otherwise CLI (with non valid long opt) segaults on RHEL8
> End long_opts array with NULL row

- src/cli/fapolicyd-cli.c
- after work on 850d2a new line is required for correct parsing in
update thread
- we were acciidentally sending string termination char as a part of the
message, we don't want that now
> CLI uses new line in update notification message

- README.md
- using of user and group names as uid and gid attributes
requires correct name resolution
> Add mention that using of names requires name resolution

- dnf/fapolicyd-dnf-plugin.py
* Point to the correct fifo path (as referenced in [paths.h](https://github.com/linux-application-whitelisting/fapolicyd/blob/main/src/library/paths.h#L37))
* Write a newline to get fapolicyd to pick up the write
cc. @kenbreeman
> Bugfixes for the dnf plugin

- src/daemon/notify.c
As of upgrading to v1.1.6, we noticed that we were no longer receiving events since we didn't opt in for monitoring bind mounted accesses via the config option. 
Without `FAN_MARK_MOUNT` added to the flags set in `fanotify_mark`, fapolicyd does not receive events for any subdirectories specified by the path parameter.
cc. @kenbreeman
> Add `FAN_MARK_MOUNT` when opting out of `FAN_MARK_FILESYSTEM`

- src/library/database.c
This can cause an invalid free and segmentation fault.
Fixes #214
> Fix returning static string instead of allocated.

- m4/dyn_linker.m4
The command path is different in the distribution. This is not the hard code, but the implementation obtained with 'command' command.
Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
> Get bash path with command

- src/library/database.c
The get_pages_in_use () return 0 sometime. In this case, 0 divisions run.
This adds a check of retuen value to avoid this problem.
Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>
> Add checking size that can be obtained with get_pages_in_use()

- src/library/event.c
- src/library/process.h
- allow other opens before dynamic linker execution
- split original STATE_REOPEN to the new STATE_REOPEN and STATE_DEFAULT_REOPEN
- STATE_REOPEN now behaves as loop state for new opens (from the same subject), uses skip_path
- STATE_DEFAULT_REOPEN is needed when dynamic linker is directly executed in such scenario we need to be sure that non of the following opens will skip the path
> Extend new_event state machine

- doc/Makefile.am
- doc/fagenrules.8
- doc/fapolicyd-cli.8
- doc/fapolicyd.8
- doc/fapolicyd.conf.5
- doc/fapolicyd.rules.5
- doc/fapolicyd.trust.5
- init/fapolicyd.bash_completion
Hi,
Lintian reports manual-page-for-system-command [0] regarding fapolicyd-cli, which means we should move that command from sbin to bin, or alternatively move its manual page from section 1 to section 8.
According to a document [1], fapolicyd-cli is expected to run with root privilege, so fapolicyd-cli is considered to be usually useful for privileged users.
As such, the manpage of the command should be moved from section 1 to section 8.
If things are satisfactory, please consider applying this patch.
Regards,
Fukui
[0] https://lintian.debian.org/tags/manual-page-for-system-command
[1] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_blocking-and-allowing-applications-using-fapolicyd_security-hardening#introduction-to-fapolicyd_asse …
> Move manpage for fapolicyd-cli from section 1 to 8

- src/library/escape.c
- src/library/escape.h
- src/library/policy.c
- fapolicyd attribues are escaped when they are printed to syslog
> Add shell escaping for syslog output

- configure.ac
- src/Makefile.am
- src/cli/fapolicyd-cli.c
- src/library/backend-manager.c
- src/library/database.c
- src/library/deb-backend.c
- src/library/event.c
- src/library/fapolicyd-backend.h
- src/library/file.c
- src/library/file.h
- src/library/trust-file.c
- src/tests/Makefile.am
- src/tests/deb_test.c
This allows fapolicyd to read the md5 hashes from dpkg as a trust source. Add a deb_test binary to run the backend standalone for debugging.
Fixes #218 
The approach used is to look at the md5 hashes from dpkg, verify they match then compute the sha256sum on the files again. This means fapolicyd is still using sha256 internally/everywhere else.
Unfortunately this means when running with `debdb` backend, this is only going to be secured with md5 which is still better than nothing.
This is still a WIP. See the TODOs.
> Initial debdb implementation.

- src/library/backend-manager.c
- reverts basically 781df888d079746b97bb9c294e91bb93652de2fd and 190a92d75ece5028527902d20ba52095b2b4f0e8
- not an error causes possibility to load a trust from .conf empty when there is no valid backend name which leads to the situation where everything on the system is untrusted
> Unsupported backend is an error

- src/library/fapolicyd-backend.h
- when debian backend was merged it casued a change in backend numbering so this commit fixes the numbers as they were before
- this numbers are also in trustdb so it is affected as well
> Fix broken backwards compatibility backend numbers

- doc/fapolicyd.8
While reading the man page, I noticed the docs say SIGTERM "caused xyz..." while the other signals "causes xyz...". Quick typo fix for tense.
> Fix doc typo for SIGTERM

- src/daemon/notify.c
Move the block of code that initializes mark_flag out of the loop so that it's always initialized, even if no watched mount points are initially present.
> Update notify.c for issue #254

- src/library/deb-backend.c
Previously calling `fapolicyd-cli -u` would cause a system lockup when using debian backend.
Fixes #259
> Reset the dpkg hash table before populating it again.

- src/tests/gid_proc_test.c
Package build fails when user has more than 16 supplementary groups.
```
.. contents:: :depth: 2
FAIL: gid_proc_test
===================
./gid_proc_test: Too many groups
FAIL gid_proc_test (exit status: 1)
```
This uses NGROUPS_MAX instead of 16 to fix the issue.
Ref: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1051181
Original-author: Russell Coker <russell@coker.com.au>
> Fix build package when user has more than 16 supplementary groups

- src/daemon/fapolicyd.c
- src/daemon/notify.c
- src/daemon/notify.h
- src/library/database.c
If for some reason, fapolicyd raises or receives a deadly signal, such as SIGBUS, the kernel task spawning the coredump handler (e.g. systemd-coredump) will hang waiting for fapolicyd to acknowledge the execution, which cannot happen since fapolicyd itself is dying.
This patch fixes the issue through unregistering from fanotify.
Example of deadlock without this patch:
~~~
[root@vm-fapolicy9 ~]# kill -SEGV 2331
[  757.531448] sysrq: Show Blocked State
[...]
[  757.544570] task:fapolicyd       state:D stack:    0 pid: 2331 ppid:     1 flags:0x00004002
[  757.545389] Call Trace:
[  757.545845]  <TASK>
[  757.546260]  __schedule+0x248/0x620
[  757.546760]  ? select_idle_sibling+0x28/0x520
[  757.547333]  schedule+0x2d/0x60
[  757.547810]  schedule_timeout+0x11d/0x160
[  757.548353]  ? …
> Protect system from deadly signals received by fapolicyd

- src/library/database.c
- src/library/paths.h
While attempting to test a freshly built `fapolicyd` on Gentoo as per the [README](https://github.com/linux-application-whitelisting/fapolicyd/#experimenting) - `/usr/sbin/fapolicyd --permissive --debug`, it would consistently fail to start.
Some debugging revealed the following:
```
umask(0117)                             = 022
unlink("/run/fapolicyd/fapolicyd.fifo") = -1 ENOENT (No such file or directory)
mknodat(AT_FDCWD, "/run/fapolicyd/fapolicyd.fifo", S_IFIFO|0660) = -1 ENOENT (No such file or directory)
write(2, "Failed to create a pipe /run/fap"..., 81Failed to create a pipe /run/fapolicyd/fapolicyd.fifo (No such file or directory)) = 81
```
This set of patches:
- has the `preconstruct_fifo` function ensure that `/run/fapolicyd` exists
- moves `fapolicyd.state` to …
> Ensure that `/run/fapolicyd` exists before performing file operations 

- src/daemon/fapolicyd.c
- src/daemon/notify.c
- src/library/database.c
This is a continuation of #273 
Blocking signals in all other threads but main thread doesn't work, because it leads to crashing then having the kernel coredump handler be called from crashing threads, without calling the main thread signal handler.
This is especially true with signals being raised internally, such as SIGSEGV or SIGBUS.
The solution consists in not blocking signals anymore, but raising the signal again for main thread in case the signal handler is running from another thread.
---
Tested on RHEL9 with 1.3.2-100.el9
The hang can be reproduced through injecting SIGBUS using systemtap, as if the RPMDB was crashing (this is based on real customer scenario).
1. Start stap injector
~~~
[...]
~~~
2. Reload RPMDB
~~~
Fapolicyd was notified
--> hang
~~~
3. Confirm stap injected …
> Stop blocking signals in other threads

- src/daemon/fapolicyd.c
- src/library/message.c
`stderr` logging got colourful and timestamped:
> Improve logging: make stderr output more colourful; add timestamps

- configure.ac
- src/Makefile.am
- src/library/deb-backend.c
- src/library/md5-backend.c
- src/library/md5-backend.h
Gentoo's portage also uses MD5s to track which files have changed since installation.
Added some debug statements for later.
> Extract MD5 logic for reuse

- doc/fapolicyd-cli.8
- init/fapolicyd.bash_completion
Missing doc on the --reload-rules option
- add to man page
- add to bash completion
> Add --reload-rules doc

- README.md
- doc/fapolicyd-cli.8
- doc/fapolicyd.conf.5
- init/fapolicyd.conf
- src/daemon/notify.c
- src/library/conf.h
- src/library/daemon-config.c
Provides recurring metric reports at a specified interval.
Uses a nonblocking timerfd alongside pthread_cond_timedwait to create timed reporting intervals. The interval is configured through the `report_interval` key in fapolicyd.conf. This value represents the length of interval in seconds between reports. If set to `0` reporting intervals are disabled, this is the default.
Reports are written to the `fapolicyd.state` file. The output format and contents of this file are unchanged by this PR. This is the same file that was written at shutdown and upon receiving `SIGUSR1`. The signal handling function remains unchanged.
Error handling is based around disabling interval reporting to preserve the decision thread. When an unrecoverable reporting error occurs the interval reports are disabled …
> Configurable metric reporting interval

- src/library/rules.c
Rules with auid=-1 (user not defined) can be useful to avoid blocking calls on behalf of the system.
> ID begins with a digit or minus sign

- src/library/queue.c
This adds a colon after the 'inter-thread max queue depth' entry in the state log.
Having uniform entries makes parsing easier, and all the other entries have a colon after the key.
> Uniform separators in state log

- configure.ac
- m4/rpm_path.m4
- src/library/policy.c
- src/library/rpm-backend.c
When the daemon is reloading the trustdb, and the rpmdb file is concurrently processed as an object, the file descriptor is closed at the end of evaluation. A close() on the SQLite database file causes the locks to be dropped. As a result, subsequent RPM installations can corrupt the RPM database when fapolicyd is running.
> Fix for rpmdb with SQLite3 backend

- README.md
- doc/fapolicyd.8
- src/daemon/fapolicyd.c
When in debug mode the default /proc/mounts source can be overridden to customize the source of fanotify events. This allows for finer level of control than is achievable with filesystem type filtering.
The intent here is to restrict events to specific locations when testing to make interpreting the event stream easier.
The alternative mounts file will expect the same format as /proc/mounts, allowing us to head, tail, or grep sublists from /proc/mounts into a new file that fapolicyd will use as the mount source.
An example of restricting fapolicyd to only listen in a test directory
```plain
$ mount -t tmpfs tmpfs /tmp/test-dir
$ grep test-dir /proc/mounts > /tmp/my-test-mounts
$ fapolicyd --debug --mounts=/tmp/my-test-mounts
```
```plain
$ cat /tmp/my-test-mounts
tmpfs /tmp/test-dir tmpfs …
```
> Allow override of mounts file

- fapolicyd.spec
- src/library/rpm-backend.c
- filter is correctly alocated and freed and it handles reload of the rpmdb backend as expected
- this was spotted by asan failures in the test suite CI
> Fix leak and problematic memory managament

- BUILD.md
- doc/fapolicyd.rules.5
- init/fapolicyd-magic
- rules.d/78-known-wine.rules
Required to establish trust for executing files from Windows in the Wine environment.
> Add Microsoft Windows PE MIME magic definition

- src/daemon/notify.c
Undo a change that came along with code formatting in 75acb36.
There was an `else` block changed to an `else if` at line 418 which caused the `pthread_cond_wait` call to fall outside of the else block.
Closes #324
> Revert change to report interval logic

- init/fapolicyd.service
- also mention about using systemctl edit
> Move After from Service to Unit where it belongs

- src/daemon/fapolicyd.c
- src/library/database.c
- Ensure that the update thread loop runs concurrently with the main loop to avoid race conditions during shutdown.
> Ensure update thread runs concurrently with main loop

- fapolicyd.spec
- src/Makefile.am
- src/daemon/fapolicyd.c
- src/handler/fapolicyd-rpm-loader.c
- src/library/rpm-backend.c
Fix rpmdb locking issues by loading via separate process
SQLite POSIX locks are bound to PIDs. When accessing rpmdb, both
librpm (used by the fapolicyd daemon) and the fanotify file
descriptors may open the database concurrently. If the fanotify FD
is closed directly, the lock is released even though librpm still
has the DB open, potentially leading to a malformed database state.
A previous workaround attempted to store the FD in a buffer:
https://github.com/linux-application-whitelisting/fapolicyd/commit/23fef4ca19ac49dd73f93362fcb51c05c3f4c580
However, this caused the daemon to read outdated or corrupted versions
of the rpmdb.
This patch expects that workaround is reverted that workaround and introduces a proper fix:
- A new binary, `fapolicyd-rpm-loader`, is introduced.
- This binary …
> Fix rpmdb locking issues by loading via separate process

- src/cli/fapolicyd-cli.c
- src/library/fapolicyd-backend.h
- either malloc fail or corruped data from lmdb can cause "fapolicyd -D" to hang in infinite loop
> Fix an infinite loop

- src/library/rpm-backend.c
On startup the kernel prints a warning that:
process 'fapolicyd' launched '/usr/sbin/fapolicyd-rpm-loader' with NULL argv: empty string added
Conventionally the first argument to argv should be the name of the program, and the kernel prints a warning whenever this is not the case.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dcd46d897adb70d63e025f175a00a89797d31a43
fapolicyd-rpm-loader doesn't use any of its arguments, but add an empty string to argv anyway to silence the kernel warning.
> Fix null argv when spawning fapolicyd-rpm-loader

- fapolicyd-uthash-bundle.patch
Fixes packit epel and centos builds:
+ /usr/bin/patch --no-backup-if-mismatch -f -p1 -b --suffix .uthash --fuzz=0 patching file configure.ac Hunk #1 succeeded at 162 (offset 50 lines). patching file src/Makefile.am patching file src/library/rpm-backend.c Hunk #1 FAILED at 33. 1 out of 1 hunk FAILED -- saving rejects to file src/library/rpm-backend.c.rej error: Bad exit status from /var/tmp/rpm-tmp.XaMr21 (%prep)
> Rebase fapolicyd-uthash-bundle.patch

- CI/ci-tests.fmf
https://github.com/RedHat-SP-Security/tests.git is obsoleted and read only
> CI: update test repo

- src/cli/file-cli.c
$ socat UNIX-LISTEN:"/home/rsroka/dir/socket" /dev/null &
[ ERROR ]: Cannot open /home/rsroka/dir/socket
Program received signal SIGSEGV, Segmentation fault.
> Fix segfault when socket is inside of the directory

- src/library/database.c
Commit 36c13aca2cbf9 ("Improve update thread synchronization in fapolicyd") added check whether stop is progress. But in corner cases when stop was in progress and there's a request for update trust db, fapolicyd exited with error.
Fixes:
[ ERROR ]: Cannot update trust database!
fapolicyd.service: Main process exited, code=exited, status=1/FAILURE
fapolicyd.service: Failed with result 'exit-code'.
> Do not exit in do_database_reload when stop in progress

- src/daemon/fapolicyd.c
- src/daemon/notify.c
- src/daemon/notify.h
- src/library/queue.c
- src/library/queue.h
Converted the event queue to a lock-free ring buffer backed by a semaphore and atomic producer/consumer indices, eliminating mutex contention and documenting the design’s latency benefits.
Added detailed memory-ordering comments and atomic operations to safely publish and consume events without locks.
Simplified the queue API so each dequeue returns a single event, removing the max argument and documenting semaphore-based ordering in both blocking and timed paths. The decision thread now dequeues a single event per iteration, removing the batching define and processing each event immediately.
Added a nudge_queue helper and updated the decision thread to grab one event .at a time via the new lock-free interface
Ensured signal handlers can wake the consumer by calling nudge_queue, allowing …
> Transform queue to a lockless design

- doc/fapolicyd-cli.8
- doc/fapolicyd.conf.5
- init/fapolicyd.bash_completion
- init/fapolicyd.conf
- src/cli/fapolicyd-cli.c
- src/daemon/fapolicyd.c
- src/daemon/notify.c
- src/library/conf.h
- src/library/daemon-config.c
- src/library/file.c
- src/library/file.h
- src/library/paths.h
See the individual commits for details: add ignore_mounts configuration option to the daemon, require ignored partitions to be mounted noexec, and create a tool to understand the risks of using this option.
> Add ignore_ mounts configuration option

- src/daemon/fapolicyd.c
IMHO it's not correct to exclude `/run` because some users may be able to write to some subdir.
Also, `/sys*` should not be excluded at all, otherwise mount points such as `/system` are being excluded as well.
> Some excluded mounts should not be excluded
