linux-application-whitelisting/fapolicyd

src/file.c
src/process.h

Branch contains suggested updates.

Interp check

---

doc/fapolicyd.rules.5

Simple fix for typo in manpage.

Fix typo in fapolicyd.rules manpage

---

Makefile.am
dnf/fapolicyd-dnf-plugin.py
fapolicyd.spec
src/Makefile.am
src/database.c
src/event.c
src/event.h
src/fapolicyd-cli.c
src/fapolicyd.c
src/notify.c
src/temporary_db.c
src/temporary_db.h

It is possible to detect an dnf update and sync our trust
database with new rpmdb.
- Added dnf plugin subpackage
- Added fapolicy CLI tool

Added possibility to sync trustdb with updated rpmdb

---

doc/Makefile.am
doc/fapolicyd-cli.1
doc/fapolicyd.8
doc/fapolicyd.conf.5
doc/fapolicyd.rules.5
fapolicyd.spec

Missing manpage added for fapolicyd-cli, resolves #36

manpage for fapolicyd-cli added

---

dnf/fapolicyd-dnf-plugin.py

DNF stdout shouldn't be affected by its plugin.

Removed stdout output for dnf plugin

---

fapolicyd.spec
init/fapolicyd.rules

Python rules will be generated in specfile %prep section from available python.

Generate python versioned paths dynamically

---

src/event.c
src/object-attr.c
src/object-attr.h
src/rules.c

Object cache "remember" whether object itself was/is trusted

Object cache contains trust information

---

src/library/database.c

During daemon cleanup after sigterm in close_database(),
close_db() was called before pthread_join(update_thread)
therefore database was closed but update_thread could be
still woken up via pipe so update of database was performed
on previously freed resources.

Fixed segfault

---

src/library/database.c

Use unlink_fifo() instead of direct unlink()

---

doc/fapolicyd.rules.5
init/fapolicyd.rules
src/Makefile.am
src/cli/fapolicyd-cli.c
src/library/attr-sets.c
src/library/attr-sets.h
src/library/event.c
src/library/object-attr.c
src/library/object.c
src/library/policy.c
src/library/rules.c
src/library/rules.h
src/library/string-util.c
src/library/string-util.h
src/library/subject-attr.c
src/library/subject-attr.h

- this commit introduces groups in rules.conf

Added attribute groups

---

src/cli/fapolicyd-cli.c

fapolicyd-cli -f without operation returns 1

---

doc/fapolicyd.rules.5
src/library/rules.c

Allow '_' in set names

---

src/library/database.c

I believe the calling of these functions is not correct.

Removed duplicate start_long_term_read_ops() 

---

src/library/process.c

Added check for " (deleted)" suffix in get_program_from_fd()

---

src/library/database.c

- cursor is already set correctly

Don't read original record when expecting duplicate

---

src/library/database.c

Rename forgoten variable

---

src/library/process.c

- this will remove only the last " (deleted)" when there are multiple suffixes

Removed strstr

---

init/fapolicyd.rules.restrictive

I believe we forgot to sync .known-libs and .restrictive language list.

Sync language list

---

init/fapolicyd-magic

Added few python and shell magic entries

---

src/daemon/fapolicyd.c

- unlink_fifo() will be called after every succesful termination
because dnf/yum can hang if the pipe exists after daemon termination
- move preconstruct_fifo() out of the scope because it is needed also
when the daemon is configured to run as root

Ensure that fifo will be removed after termination

---

.github/workflows/rawhide-fedora-build.yml
.github/workflows/stable-fedora-build.yml
fapolicyd.spec

Use github actions as a new CI.

Setup github actions

---

.github/workflows/.rawhide-fedora-build
.github/workflows/centos-build.yml
fapolicyd.spec

Fix CI problems

---

src/library/rpm-backend.c

Make the drop_path function more readable and extendable.

drop_path function refactoring

---

src/cli/fapolicyd-cli.c

For easier readability I have split the do_manage_file function into smaller ones. I also fixed some problems, namely with fapolicyd-cli -f update (where you couldn't omit the path argument as you should) and the error messages should be easier to manage.

cli do_manage_file function refactoring and fix

---

doc/fapolicyd.trust.5

Add description of trust.d directory into fapolicyd.trust.5 manual page.

Add trust.d into man page

---

doc/fapolicyd.trust.5

Minor additions and correction.

Update fapolicyd.trust.5 man page

---

src/library/trust-file.c

Variable `int i` before escaping patch was inside the loop and that was done deliberately. Within the escaping patch it has been moved outside of the loop which broke the `trust_file_append` function as the variable `i` is used within `make_path_string` function as both input and output. Moving it outside of the cycle caused that output of the previous iteration was used as an input in the current iteration.
Bug: lets say I have directory /opt/testdir/ that contains tesfile and subdir/testfile ... now I do
`fapolicyd-cli -f add /opt/testdir/`
and when I check `/etc/fapolicyd/fapolicyd.trust` I see something like this:
```
/opt/testdir/testfile 0 sadfnsaldkjf....
/opt/testdir/subdir/testfile pt/testdir/subdir/testfile dfgnfskdjfhgber...
```
The issue is reproducible when you use …

Fix trust_file_append function

---

src/library/trust-file.c

Bug: whenever you want to append a file into a trust file that does not exist, the fapolicyd-cli fails instead of creating it inside trust.d directory.
This patch fixes this issue as we can ignore the "cannot open path" error inside trust_file_append because it will be created in write_out_list function.

Fix trust_file_append function (again)

---

init/fagenrules

Set correct mode and group for compiled.rules

---

.github/workflows/centos-build.yml
.github/workflows/stable-fedora-build.yml
src/library/database.c

- fd_fgets() guaratees that input will be read line by line
- FIFO fd needs to be non blocking because thread will be blocked on
read()

Use fd_fgets() in update thread

---

src/daemon/fapolicyd.c
src/library/database.c

Recover SIGHUP handling

---

src/library/trust-file.c

- simplified make_path_string() into make_data_string() and removed count
parameter that was not used
- removed also escaping part of the function that was not used, escaping is done by
write_out_list()

Little bit of refactoring of trust-file.c

---

doc/fapolicyd.conf.5
doc/fapolicyd.trust.5

Fix the man section number of fapolicyd.conf from 6 to 5, and fapolicyd.trust.5 from 13 to 5,
Signed-off-by: Nobuhiro Iwamatsu <iwamatsu@nigauri.org>

doc: Fix section number

---

doc/fapolicyd.conf.5
src/daemon/fapolicyd.c
src/daemon/notify.c

Hi maintainers,
We're trying to fix spelling errors found in the source code.
If things are satisfactory, please consider merging this pull request.
Thanks,
Fukui

Fix spelling errors

---

src/daemon/fapolicyd.c
src/library/escape.c
src/library/escape.h

Implement unascape capability for mounts

---

src/daemon/notify.c

In case error is produced, daemon should allow execution if we are running in permissive mode

Fix error path when appending to queue

---

src/cli/fapolicyd-cli.c
src/daemon/fapolicyd.c
src/daemon/notify.c
src/library/database.c
src/library/database.h
src/library/event.c
src/library/policy.c
src/library/policy.h
src/library/rules.c

- rules are reloaded in case of SIGHUB
- the pipe logic was extended as well since it accepts number 3 now (for rules reloading)
- CLI has new option "-r" that provides this capability

Introduce runtime rules reloading feature

---

fapolicyd-uthash-bundle.patch
fapolicyd.spec

this is PR implements some tweaks of spec file and also preparation for the CI
the changes are a prerequisite for CI changes, currently prepared in https://github.com/sopos/fapolicyd/pull/2

Spec tweaks

---

.github/workflows/almalinux8.yml
.github/workflows/almalinux9.yml
.github/workflows/rockylinux8.yml
.github/workflows/stable-fedora-build.yml
.github/workflows/ubuntu22.yml
README.md
deb/README.Debian
deb/build_deb.sh
deb/postinst
deb/rules

Tested on AWS Ubuntu 22.04 image and working as expected.

Initial creation of debian package.

---

fapolicyd.spec

this allows to test latest chenges includsing the latest selinux DSP policy changes

use master head of the fapolicyd-selinux

---

src/library/file.c

- some CI instances fail on this error

Fix 'error label at end of compound statement'

---

configure.ac

- fapolicyd can be linked with address sanitizer

Add --with-asan for configure

---

src/library/database.c
src/library/rpm-backend.c

We need to use rpm transaction lock so we can be sure we are reading valid(not corrupted) data.
If we cannot acquire lock, we have to stay with an old version of trustdb. We expect that files installed in current transaction are present in the old trustdb already, they were recieved from fapoliycd rpm plugin. So it is safe to wait till the end of the transaction and then trustdb will be reloaded.

Introduction of rpmdb transaction locking
